### ISSUE TITLE
CommandClass THERMOSTAT_SETPOINT (0x43) not implemented since 1.7.0-863

### ISSUE THREAD

**Issue by Thomas38** [openhab/openhab#2166]
Hello,

after updatin to #863 all my danfoss thermostat are unknown and the temperature could not be read or set. It seems that the command classes are not longer known. The items are look like this one:

Number ThermoBathroom "Badezimmer [%.1f C]" { zwave="9:command=thermostat_setpoint,setpoint_type=1,setpoint_scale=0" }

Following message appears:

2015-02-21 15:17:45.860 [ERROR] [b.z.i.protocol.ZWaveController] - NODE 9: Error deserialising XML file. com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveThermostatSetpointCommandClass.setpointTypes
---- Debugging information ----
field : setpointTypes
class : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveThermostatSetpointCommandClass
required-type : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveThermostatSetpointCommandClass
converter-type : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path : /node/supportedCommandClasses/entry[10]/thermostatSetpointCommandClass/setpointTypes
line number : 96
class[1] : java.util.HashMap
converter-type[1] : com.thoughtworks.xstream.converters.collections.MapConverter
class[2] : org.openhab.binding.zwave.internal.protocol.ZWaveNode

2015-02-21 16:27:48.938 [ERROR] [.ZWaveMultiCommandCommandClass] - NODE 9: CommandClass BATTERY (0x80) not implemented.
2015-02-21 16:27:48.942 [ERROR] [.ZWaveMultiCommandCommandClass] - NODE 9: CommandClass THERMOSTAT_SETPOINT (0x43) not implemented.
2015-02-21 16:27:48.946 [ERROR] [.ZWaveMultiCommandCommandClass] - NODE 9: CommandClass CLIMATE_CONTROL_SCHEDULE (0x46) not implemented.
2015-02-21 16:27:48.950 [ERROR] [.ZWaveMultiCommandCommandClass] - NODE 9: CommandClass CLOCK (0x81) not implemented.
2015-02-21 16:27:48.954 [ERROR] [.ZWaveMultiCommandCommandClass] - NODE 9: CommandClass CLIMATE_CONTROL_SCHEDULE (0x46) not implemented.
2015-02-21 16:27:48.959 [ERROR] [.ZWaveMultiCommandCommandClass] - NODE 9: CommandClass WAKE_UP (0x84) not implemented.

**Comment by cdjackson** [comment]
The XML error is not a problem - it's just that you've upgraded and the format has changed.

I don't understand the bottom part about command classes not implemented - these classes are implemented. Unfortunately your logfile doesn't provide the line numbers so it's difficult to trace.

Can you provide a debug log please of the full startup.

**Comment by Thomas38** [comment]
the bottom part appears every time the thermostat sends an update, in my case every 5 minutes.
It works well with my last version 1.7.0-852. Nothing else changed except update to  #864.
I will set up a debug log and put it here.

**Comment by cdjackson** [comment]
Thanks.

What thermostats are they? I know a number of people have been using the latest version (from HABmin site) with Danfoss thermostats at least.

Another thought - can you try the version on the HABmin page - download from here (https://github.com/cdjackson/HABmin/tree/master/addons <https://github.com/cdjackson/HABmin/tree/master/addons>). This is such a fundamental error I’m wondering if there’s a build error with the cloudless version.  I have lots of battery devices, and don’t have an error saying it’s unsupported (which isn’t surprising, since it is supported :) ).

**Comment by Thomas38** [comment]
I'm using Danfoss LC13. New binding is installed and openhab restartet with logging.
Log will be sent via mail because to big...

**Comment by Thomas38** [comment]
Von: Chris Jackson [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Februar 2015 17:13
An: openhab/openhab
Cc: Thomas38
Betreff: Re: [openhab] CommandClass THERMOSTAT_SETPOINT (0x43) not implemented since 1.7.0-863 (#2166)

 

Thanks.

What thermostats are they? I know a number of people have been using the latest version (from HABmin site) with Danfoss thermostats at least.

Another thought - can you try the version on the HABmin page - download from here (https://github.com/cdjackson/HABmin/tree/master/addons <https://github.com/cdjackson/HABmin/tree/master/addons>). This is such a fundamental error I’m wondering if there’s a build error with the cloudless version. I have lots of battery devices, and don’t have an error saying it’s unsupported (which isn’t surprising, since it is supported :) ).

**Comment by cdjackson** [comment]
Thanks - LC13 should be working ok with this binding - I know people have tested it before it was merged.

I’ve not received the log yet. If it’s more than about 20MB, then please reduce it or zip it and email it to chris -at- cd-jackson.com

Cheers
Chris

**Comment by cdjackson** [comment]
Hi Thomas,
Ok - I don’t think anything has changed, but you’ve made the fatal error of looking in the log :)

I think this error has always been there, but once the device initialises, it will go away. Currently, node 9 is still in the early stages of initialisation and it hasn’t discovered what classes the device supports… This message is received as a multi command encapsulation, and at this point it doesn’t have the ability to add the classes…

So, I think once the device wakes up (not just sends temperature or whatever, but sends the wakeup notification which is when the binding can initialise the device) then these errors will go away and the device will work. Once the XML file is saved (i.e. after the device completes initialisation the first time) this won’t happen again even when you restart the binding…

So, before I change anything, can you wake the device so that it completes initialisation, and then see if this problem stops.

Chris

**Comment by Thomas38** [comment]
Ohh, if I have to press a button on the device it could take a few weeks. The Danfoss is in another building and in another city and nobody will be there for next time.

I will downgrade to my latest version of openhab or I try to replace the binding only, otherwise I have no control of the heating there.

Is there a workaround for me by replacing the xml file ?

Thank you,
Thomas

**Comment by cdjackson** [comment]
> Ohh, if I have to press a button on the device it could take a few weeks. The Danfoss is in another building and in another city and nobody will be there for next time.
> 
> I will downgrade to my latest version of openhab or I try to replace the binding only, otherwise I have no control of the heating there.
> 
No - you don’t need to press the button - this will just speed it up. I assume it will wake up after 1 hour or so (do you know what the wakeup period is?).

This issue will also be in the previous version - the device needs to complete initialisation before it will work.

**Comment by Thomas38** [comment]
The wakeup is set to 5 minutes. In the log you shoud see at least two cycles. It also runs already during the last 2 days and it does not fix the problem.

**Comment by cdjackson** [comment]
The device never woke up in the log you sent - it did send information, but that's not the same thing... 

I think you're mixing up the period in which it sends temperature updates, and the wakeup notification. Wakeup is a separate command class and is used by the device to tell the controller that it can RECEIVE data (eg so the controller can initialise it). Normally, this is set to an hour or so, although some people set it to a day.

**Comment by Thomas38** [comment]
With the previous version I have no problem !!!!

I can easaly switch between different version of OpenHAB.
The Version 1.7.0-852 works, the Version 1.7.0-863 shows the problem I have.

**Comment by cdjackson** [comment]
If it's been running for 2 days, then possibly the wakeup class isn't set...

**Comment by Thomas38** [comment]
I have also access to the devices using zway. I used it yesterday to verify the setup. After 5 minutes everything is set up within this tool.

If it makes sense I will switch back to the old version und set up a zwave debug log.

**Comment by cdjackson** [comment]
Just bacuase it was running fine on the previous version doesn't mean the issue doesn't exist. As I said, the device needs to initialise. It can only initialise under 2 conditions - either you press the button, or the wakeup command class sends the wakeup notification. Once the device is initialised once, it writes its configuration to the XML file, and this isn't required again.

I might be wrong, and maybe the old version will work, but the muli command encapsulation command class hasn't changed in the new version, and it doesn't add the classes. So, I can't see that this will work in the old version either.

**Comment by cdjackson** [comment]
Can you confirm with zway what the wakeup period is? Does it tell you?

**Comment by cdjackson** [comment]
One other point... What I was going to say in the beginning is that I wanted you to wake up the device to check that my theory was correct. If it works after the wakeup as I think, then it means I understand the problem and I wanted to try and do this before I change anything.

However... I can also fix this by adding the classes - this is my intention, but it would have been better to have confirmed the issue before I did this...

So, let's do this -:
Do you have the XML file for node 9 from the previous version? If so, please can you email it to me (don't paste it into Github - it will mess up the format)?

I'll look at modifying the software to add a fix. I need to have dinner in a few minutes, so it will be an hour or two, but it won't take long to do...

Chris

**Comment by Thomas38** [comment]
Could you give me a pointer where I can find the xml ?
Just playing with zway. I can request NIF, is that what we need to get the xml setup ?

**Comment by cdjackson** [comment]
> Could you give me a pointer where I can find the xml ?
> 
It should be in the openhab/etc/zwave folder. Hopefully the one from the previous binding might still be there… If you’re on ubuntu it might be somewhere else...

> Just playing with zway. I can request NIF, is that what we need to get the xml setup ?
> 
Yes, and no… The binding also requests the NIF, but of course the device can’t send one until it wakes up. My understanding is that this can only happen when the wakeup command class triggers, and it seems maybe yours isn’t configured to wake (??). Give it a try on ZWay and see what happens - if it does work, it will tell me something (i.e. that it’s possible to try and send when the device sends data, but based on the docs I have, this is not guaranteed as most devices won’t support it).

**Comment by Thomas38** [comment]
That is the way I used the command in zway, I request NIF so the device introduces itself to zway. For sure the wakeup time is 5 minutes. All I request in zway (Interview and NIF) will be delivered within the next 5 minutes.
I just switched back to my last version of openhab. The log looks different, also the command class setpoint is known now. I will put the xml here as soon initialization has finished.

**Comment by Thomas38** [comment]
Node 13 has just finished init:

OpenLAB:/openhab/etc/zwave # cat node13.xml
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>-746330873</homeId>
  <nodeId>13</nodeId>
  <version>4</version>
  <manufacturer>0x2</manufacturer>
  <deviceId>0x4</deviceId>
  <deviceType>0x5</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>FAILED during PING @ 2015-02-20T01:01:13+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>SENSOR_BINARY</commandClass>
      <binarySensorCommandClass>
        <version>0</version>
        <instances>0</instances>
      </binarySensorCommandClass>
    </entry>
    <entry>
      <commandClass>METER</commandClass>
      <meterCommandClass>
        <version>0</version>
        <instances>0</instances>
        <meterType>ELECTRIC</meterType>
        <meterScales>
          <meterScale>E_KWh</meterScale>
        </meterScales>
        <canReset>false</canReset>
      </meterCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>0</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>0</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>THERMOSTAT_SETPOINT</commandClass>
      <thermostatSetpointCommandClass>
        <version>2</version>
        <instances>0</instances>
        <setpointTypes>
          <setpointType>HEATING</setpointType>
        </setpointTypes>
      </thermostatSetpointCommandClass>
    </entry>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>0</instances>
        <batteryLevel>68</batteryLevel>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>0</instances>
        <libraryType>LIB_UNKNOWN</libraryType>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>MULTI_CMD</commandClass>
      <multiCommandCommandClass>
        <version>1</version>
        <instances>0</instances>
      </multiCommandCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>0</instances>
        <targetNodeId>1</targetNodeId>
        <interval>300</interval>
        <minInterval>0</minInterval>
        <maxInterval>0</maxInterval>
        <defaultInterval>0</defaultInterval>
        <intervalStep>0</intervalStep>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>0</instances>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>0</version>
        <instances>0</instances>
      </binarySwitchCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>14</int>
    <int>15</int>
    <int>16</int>
    <int>19</int>
    <int>22</int>
    <int>23</int>
  </nodeNeighbors>
  <lastSent>2015-02-21 18:44:51.7 UTC</lastSent>
  <lastReceived>2015-02-21 18:44:56.523 UTC</lastReceived>
</node>OpenLAB:/openhab/etc/zwave #

**Comment by Thomas38** [comment]
Temp of node 9 and 13 is set, everything is fine !
xml sent via mail, looks that ugly here.

**Comment by Thomas38** [comment]
Btw, if I switch between different versions I keep  the xml files in etc !

**Comment by cdjackson** [comment]
As I said, please email me the XML as github trashes the file :(

**Comment by cdjackson** [comment]
> 
> Btw, if I switch between different versions I keep the xml files in etc !
> 
Yes, but the new version won’t use it as it’s an old version of the XML..

I’ll take a look at the log. The issue is that in the log you sent me earlier, device 9 never woke (see image below) - we only recieved the MULTI_CMD command class. If the wakeup is definately set, then I don’t know why it’s not waking up, but we’ll see what the other log shows.

**Comment by cdjackson** [comment]
Don’t worry about sending through the XML file… I know what’s happening, but I don’t understand why this wouldn’t be the same in the old version. The wakeup is encapsulated in the multi command class, so that’s why we don’t get the wakeup message even though it’s awake.

I suspect that the reason the old version works is because it’s using the XML file that was produced some time ago, and after it got through initialisation. I can’t see any way the device can initialise with the binding as it currently is, so the old version must do the same… Anyway, please send the old version log and I’ll try and confirm…

Give me an hour or so and Ill hopefully get a fix.

**Comment by Thomas38** [comment]
Again: I'm using the same files in etc by switching the version !

The configurations and etc directories are soft linked into my different version of OpenHAB.
Therefore the ./zwave/*.xml files are kept during the update.

**Comment by cdjackson** [comment]
> 
> Again: I'm using the same files in etc by switching the version !
> 
Yes, and again :) the new version doesn’t use the old XML file as it’s from the old version. This was something you posted about right at the beginning -:

2015-02-21 17:26:34.758 [ERROR] [b.z.i.protocol.ZWaveController:286 ]- NODE 9: Error deserialising XML file.

So, my point is that the old version doesn’t need to initialise as it’s using the XML. The new version must initialise as it can’t use the XML.  The issue therefore exists in the old version as well, but you don’t see if since the XML bypasses the issue…

I hope that makes sense. If you send me a log from the old version startup I can confirm this, but I’m pretty sure it’s the case. I’ll have a fix shortly but I’ll email it to you to test before I make it available to the masses…

Thanks.

Cheers
Chris

**Comment by Thomas38** [comment]
Ok Chris, I got it. It seems that I'm getting slow in the evening. Debug log sent to you.

**Comment by Thomas38** [comment]
Everything works !

**Comment by cdjackson** [comment]
Brilliant - thanks for your help with this one. I’ll create a patch into the master repo.

Cheers
Chris

**Comment by cdjackson** [comment]
Closed by #2169
