### ISSUE TITLE
Dimmer item keeps sending INCREASING/DECREASING command

### ISSUE THREAD

**Issue by Eggn1n3** [openhab/openhab#2210]
Hi,

I am having issues with the DIMMER item. When I click in my sitemap on button up to increase the volume of my Sonos system, I get a lot of INCREASE commands that do not stop. The same for DECREASE when clicking button down. This espically happens when I click rappidly on up/down button. I already changed the frequence setting but that doesn help.

I am using OpenHAB 1.7.0

.item:
Dimmer       woonkamerVolume " [%d %%]"      { sonos="[OFF:woonkamer:volume], [ON:woonkamer:volume], [DECREASE:woonkamer:volume], [INCREASE:woonkamer:volume]", autoupdate="false" }

.sitemap:
Slider item=woonkamerVolume label="Volume [%d %%]" icon="settings" sendFrequency=1000	

Nothing in rule file

events.log:
2015-02-28 20:41:42 - woonkamerVolume received command INCREASE
2015-02-28 20:41:42 - woonkamerVolume received command INCREASE
2015-02-28 20:41:42 - woonkamerVolume state updated to 98
2015-02-28 20:41:42 - woonkamerVolume received command INCREASE
2015-02-28 20:41:42 - woonkamerVolume state updated to 99
2015-02-28 20:41:42 - woonkamerVolume received command INCREASE
2015-02-28 20:41:42 - woonkamerVolume state updated to 100
2015-02-28 20:41:42 - woonkamerVolume received command INCREASE
2015-02-28 20:41:42 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:43 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:44 - woonkamerVolume received command INCREASE
2015-02-28 20:41:45 - woonkamerVolume received command INCREASE
2015-02-28 20:41:45 - woonkamerVolume received command INCREASE

When I close the browser with my sitemap, the flooding of INCREASE commands stop.

Any idea what could be causing this?

Thanks.

**Comment by kaikreuzer** [comment]
This could be linked to #2127

**Comment by Eggn1n3** [comment]
In downloaded snapshot 1.7.0 build #869 and tested the slider, but again, I am flooded with the INCREASE command; even after pressing the UP button once. Am I using the right version where fix  #2127 has been applied?

**Comment by kaikreuzer** [comment]
What I meant is that #2127 might have introduced the problems.

**Comment by Eggn1n3** [comment]
Ah, ok, sorry, the subject of #2127 says ¨Fixes dimmer/rolershutter infinite request bug¨. I was under the impression that this was fixed.

**Comment by Eggn1n3** [comment]
Update: I did some more testing and this only happens when using the (classic) web interface. Using the Android client for example does not show this unwanted behaviour; e.g. works perfectly.

**Comment by kaikreuzer** [comment]
@sja: Any update on this? Should #2127 be reverted?

**Comment by sja** [comment]
I'll spend this some time today. Had other issues to work on.

**Comment by sja** [comment]
@Eggn1n3 Would be nice to know your Browser name and version you used.

**Comment by Eggn1n3** [comment]
Hi Sja,
All browsers I tried failed, but to be more precise:
On Windows 7 (64 bits):
- Firefox ESR, 31.5.0
- IE11 (11.0.9600.17633)
When I am back home I will check the version of my Linux Mint OS (but I am also using Firefox).
The same for OSX on my iMac and iPad  (which runs Safari).

Thanks!
IE

**Comment by sja** [comment]
No, thats ok. I just need one Browser, where this definitely happens and which I can use, too.

**Comment by Eggn1n3** [comment]
Ok, Safari seems ok; it's mainly Firefox and IE11. Chrome seems fine too.

**Comment by sja** [comment]
Works for me with Chrome 40, FF 33.1.1, FF 31.5 ESR and IE11 on Win8.1. Tested with Rollershutter and Dimmer item "Widget Overview" of demo config.

**Comment by sja** [comment]
@Eggn1n3 Your behaviour was a bug some weeks ago, thats right. But exactly this behaviour was fixed. Can you double check, that you've installed the correct version? Did you "hotplug" the jar or did you a fresh install and restart of openHAB?

**Comment by Eggn1n3** [comment]
Hi Sja,
I downloaded 1.7.0 from here https://openhab.ci.cloudbees.com/job/openHAB/ about two weeks ago.
Not sure what the exact snapshot version I have though. Is there a number I can check?

Thanks.

**Comment by sja** [comment]
Hmm, I don't know if the changes were in there. To be sure: Open Firefox Developer tools console (alt+cmd+k on a mac) and type at the bottom `OH` and Enter. 

The Console should print something like 

    Object { changeState: changeState(), images:...

if you have my changes or 

    ReferenceError: OH2 is not defined

if you still have the old version.

**Comment by Eggn1n3** [comment]
Hi,

I indeed had the older verision showing "OH is not defined". After I installed the latest 1.7.0 snapshot it shows the Object { changeState: changeState().

However, the problem is still there. What I noticed is the error "No element found". Not sure if that's related?

![screenshot from 2015-03-05 21 24 29](https://cloud.githubusercontent.com/assets/10974459/6513930/117bddc6-c37f-11e4-87c0-e1b20c4bfadd.png)

**Comment by git734** [comment]
Hi,
I have (again) the INCREASE/DECREASE pb.
I have tested I have said version (typing OH => Object { changeState: changeState(), ...)
Do you have other idea to check the version and/or correct this pb ?
thanks

**Comment by dominicdesu** [comment]
I had the same issue with the latest nightly build.
Actually this behaviour can be caused in two different situations:
1) See #2473: A bug in Firefox with the handling of synchronous XML Requests
2) Click and holding the up/down arrow and dragging it to some other location. The onmouseup is not triggered if the mouse button is released in a location different from where it has been clicked (http://stackoverflow.com/questions/6019190/mouseup-event-on-drag). If the onmouseup is not triggered, the request loop to the server is never cancelled.

The more common issue (1) should be fixed with the pull request in #2473, while issue 2 is still open but quite unlikely to happen very often.

**Comment by teichsta** [comment]
reopen, since 2) (see comment above) is still open. @dominicdesu @sja any easy chance to fix this?

**Comment by sja** [comment]
#2473 is nearly closed, just the upstream to ESH is missing. 

As the stackoverflow top answer mentioned, the only solution could be to catch mouseup on <body> element. Because of event bubbling that element should receive it. This has some requirements:
 1. There must be no parent element catching that event and preventDefault() that. Because that would stop bubbling.
 2. ~~The mouseup has to contain the original target element. Otherwise we don't know what to stop.~~

Requirement 2 is not neccessarily required, because in our case, we can break the module pattern. We just say, that all looping queries have to stop, not just the original triggered one. For classic ui that should be ok.

After that, we can hopefully close this issue. It's a small change, but atm I have no time for that, because that has to be tested. Maybe on the weekend. Or somebody else can test it? It should be something like this in `snippets/main.html`:

    $('body').mouseup(function(){
      OH.dimmer.resetTimer();
      OH.rollershutter.resetTimer();
    });

@dominicdesu You can even test this without changing any files, just copy past the lines in the js console (where you verified the OH object) and try dragging the button while pressed.

**Comment by dominicdesu** [comment]
@sja I tried inserting your code via the js console and also added it directly to the ui.webapp.jar but no difference for the drag & drop behaviour.
I am also not able to get the debugger stop in the function, it looks like it is never called?
Probably it's best if you have a look as soon as you find some time, as my experience with javascript is very limited.

**Comment by teichsta** [comment]
any chance to have a look at this until the coming weekend @sja?

**Comment by teichsta** [comment]
any update @sja? Would be great to have this fixed for 1.7

**Comment by sja** [comment]
Ah right, starting on this now. Thanks for bumping :-)

**Comment by teichsta** [comment]
any chance to get this fixed today?

**Comment by kaikreuzer** [comment]
Any action required for Eclipse SmartHome?

**Comment by sja** [comment]
Yes. The same has to be applied to that classicui. 
In general, Classicui belongs to ESH, not OH2, right? Then I will rename the Namespace 'OH' to 'ESH'. 

Von meinem Telefon gesendet

**Comment by kaikreuzer** [comment]
> In general, Classicui belongs to ESH, not OH2, right? 

Correct.
