### ISSUE TITLE
Core-Rules: Execution context trashed by RuleEngine.executeRules/executeRule (Thread Safety Problem)

### ISSUE THREAD

**Issue by mrguessed** [openhab/openhab#2362]
I was having issues where I had multiple Rules, each triggering off the _same_ Item event, and was seeing unusual behavior wrt the execution state (context) I should have at that time.

... mostly, my _Lock_ variables were `null`, even though they were declared as Rule-level variable declarations that are pre-initialized.  In my case I had several different rules, across different Rule files, that triggered off the same Item (`HallMotionZoneTripped`) being changed... so they should all fire at the same time...

```xtend
import ...
import java.util.concurrent.locks.ReentrantLock
...
var ReentrantLock hLock = new ReentrantLock(false)

rule "Garage Interior"
when
    Item HallMotionZoneTripped changed from CLOSED to OPEN
then
    ...
    // Sometimes hLock will be null here, and cause an error like:
    //   ERROR o.o.c.s.ScriptExecutionThread[:50]- Error during the execution of rule 'Garage Interior': cannot invoke method public void java.util.concurrent.locks.ReentrantLock.lock() on null

    hLock.lock
   ...
end
```

Looking deeper, it appears (by visual code inspection) that, in this situation, `org.openhab.model.rule.internal.engine.RuleEngine` is sharing an execution context, across all Rules triggered by a single event, and it's mutating that context as it launches off each thread.

To make it more concrete, run the following testcase:

_items/ctxItems.items_:
```xtend
Number ContextSharing
```

_rules/ctxa.rules_:
```xtend
val String nm = "context a"

rule "context a"
when
        Item ContextSharing received update
then
        logInfo("context-a", nm)
end
```

_rules/ctxb.rules_:
```xtend
val String nm = "context b"

rule "context b"
when
        Item ContextSharing received update
then
        logInfo("context-b", nm)
end
```

_rules/ctxtrigger.rules_:
```xtend
val String nm = "context trigger"

rule "context trigger"
when
        Time cron "0/10 * * * * ?"
then
        logInfo("context-trigger", "Before" + nm)
        postUpdate("ContextSharing", String::valueOf(now.getMillis()))
        logInfo("context-trigger", "After" + nm)
end
```

Note that I use the tag `context-a` for _LogInfo_ lines from Rule _rules/ctxa.rules_, and the tag `context-b` for _LogInfo_ lines from Rule _ctxb.rules_.

Internally, each Rule is just printing the String from it's Rule-global variable `nm` and that name should match the name provided to the _logInfo_ call.

Check out the output below, the parts in <b>BOLD</b> are incorrect since Rule "context b" is running with Rule "context a"'s context.

19:42:30.003 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
19:42:30.004 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
19:42:30.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
19:42:30.006 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context b'
19:42:30.007 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context a'
<b>19:42:30.007 INFO  o.o.model.script.context-b[:53]- context a</b>
19:42:30.008 INFO  o.o.model.script.context-a[:53]- context a
19:42:40.005 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
19:42:40.006 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
19:42:40.008 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
19:42:40.008 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context b'
19:42:40.008 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context a'
<b>19:42:40.009 INFO  o.o.model.script.context-b[:53]- context a</b>
19:42:40.009 INFO  o.o.model.script.context-a[:53]- context a
19:42:50.001 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
19:42:50.002 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
19:42:50.004 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
19:42:50.004 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context b'
19:42:50.004 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context a'
<b>19:42:50.004 INFO  o.o.model.script.context-b[:53]- context a</b>
19:42:50.005 INFO  o.o.model.script.context-a[:53]- context a
19:43:00.001 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
19:43:00.002 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
19:43:00.004 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context b'
19:43:00.004 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
19:43:00.004 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context a'
19:43:00.005 INFO  o.o.model.script.context-b[:53]- context b
19:43:00.005 INFO  o.o.model.script.context-a[:53]- context a
19:43:10.003 DEBUG o.o.m.r.i.e.ExecuteRuleJob[:53]- Executing scheduled rule 'context trigger'
19:43:10.004 INFO  o.o.m.script.context-trigger[:53]- Beforecontext trigger
19:43:10.006 INFO  o.o.m.script.context-trigger[:53]- Aftercontext trigger
19:43:10.006 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context b'
19:43:10.006 DEBUG o.o.m.r.i.engine.RuleEngine[:285]- Executing rule 'context a'
19:43:10.007 INFO  o.o.model.script.context-b[:53]- context b
19:43:10.007 INFO  o.o.model.script.context-a[:53]- context a

Checking over the code, this appears to be due to [RuleEngine.java](https://github.com/openhab/openhab/blob/master/bundles/model/org.openhab.model.rule/src/org/openhab/model/rule/internal/engine/RuleEngine.java) sharing a context when a single Item event results in multiple Rule executions.

The `executeRules()` variants create a single RuleEvaluationContext, and pass it down to `executeRule()`.

This then sets a specific Rule's context on this [shared, mutable] RuleEvaluationContext, and forks a thread with it.

```java
protected synchronized void executeRule(Rule rule, RuleEvaluationContext context) {
	Script script = scriptEngine.newScriptFromXExpression(rule.getScript());

	logger.debug("Executing rule '{}'", rule.getName());
			
	context.setGlobalContext(RuleContextHelper.getContext(rule)); // BAD, Mutation of input parameter
			
	ScriptExecutionThread thread = new ScriptExecutionThread(rule.getName(), script, context);
	thread.start();
}
```

For my use-case, this is called in a loop from the `executeRules()` code, with a single/shared `RuleEvaluationContext`, and bad things happen to the next guy in the loop ;)

Shutdown rules are probably impacted by this also.

**Comment by watou** [comment]
Thanks for tracking this down, Mark.  Thread safety problems can obviously lead to impossible and thus frustrating rule debugging situations.

**Comment by teichsta** [comment]
Thanks a lot @mrguessed for tracking this down! Although problem described doesn't happen too often on my machine i was able to reproduce it after some while of log reading. Will have a look into the PR now. Best, Thomas E.-E.

**Comment by sumnerboy12** [comment]
I think this might be related to;
https://groups.google.com/forum/#!searchin/openhab/rule$20context/openhab/nQwfPt9ujOs/dr89tORs3TsJ
https://groups.google.com/forum/#!searchin/openhab/rule$20context/openhab/3OHBFnliUe8/oK8FrK3l6s0J
If this does fix those issues then this is a great step forward - well done @mrguessed !

**Comment by sumnerboy12** [comment]
And potentially relates to https://code.google.com/p/openhab/issues/detail?id=487 also.

**Comment by dominicdesu** [comment]
In the last link by @sumnerboy12 [this ESH bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=423532) about shared context is mentioned and has been fixed with pull request https://github.com/eclipse/smarthome/pull/9. As far as I can see, this is a different solution than pull request #2363 . How do the two solutions relate? Are they solving the same or different problems?

**Comment by sumnerboy12** [comment]
They both relate to shared context within rules - I think they are therefore related? Although the solutions maybe different perhaps?

**Comment by dominicdesu** [comment]
Sorry, didn't want to question that these issues relate. As you already found these related posts, I just thought it would be useful to compare both solutions and to understand why and how they are different. :-)

**Comment by sumnerboy12** [comment]
I don't know much about the OH2 code but I think it is written in quite a different manner, so the fixes in these two code bases are potentially quite different. As long as it is fixed in both I will be very happy :).

**Comment by teichsta** [comment]
ah, i wasn't aware of the above mentioned bug (and the according PR). @mrguessed would you mind having a look into the given solution? Would be great to have them both in sync. Thanks, Thomas E.-E.

**Comment by dominicdesu** [comment]
Actually this is a bit confusing... the linked pull request in the ESH bug report does not seem to include the shared context fix. Either it was done in a different pull request or some part of the history on github is missing.
Anyway, looking at the [current implementation of ESH](https://github.com/eclipse/smarthome/blob/fef8f1b83faa7b5859c0492400d9dcce132c2b59/bundles/model/org.eclipse.smarthome.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java), the solution to the shared context issue is not exactly the same yet quite similar.

**Comment by mrguessed** [comment]
I'm not familiar enough with ESH to make the full comparison, but at a glance the code that @dominicdesu references about appears similar-enough, and has the same general pattern (and short-term fix).

The source of the problem was a mutable context object.  In OH I didn't fix that, but opted to be careful of on how/when to use it (to minimize the overall change to the OH code).

I suspect the t-safe issue was introduced by someone accidentally mutating the context when not looking at the wider usage.  

This pattern is also in the ESH code, but [IMHO] the _real_ fix is avoid using mutable context objects, so folks can't accidentally do anything bad.

As a side-note, the ESH code has _synchronized_ all over it.  It seems like that could all be localized around the central _executeRule_ (and internalized, not declared on the Method) to avoid early locking.  Even then, it's going to serialize (all?) Rule execution based upon how quickly Rule-threads can be started up.... not sure if that's intended or not.

**Comment by teichsta** [comment]
> As a side-note, the ESH code has synchronized all over it. It seems like that could all be localized around the central executeRule (and internalized, not declared on the Method) to avoid early locking. Even then, it's going to serialize (all?) Rule execution based upon how quickly Rule-threads can be started up.... not sure if that's intended or not.

would be great to bring this up on the ESH forum!

So if i got you all correctly we can close this issue for now.

**Comment by mrguessed** [comment]
Yes, it's ok to close out this thread.  I will add something to the ESH list for my comments above.

**Comment by teichsta** [comment]
Thanks so much, Mark!
