### ISSUE TITLE
Embedded NULLs in zwave XML persistence files cause deserialization errors on openHAB startup.

### ISSUE THREAD

**Issue by TheKorn2** [openhab/openhab#4046]
Embedded NULLs in zwave persistence files cause deserialization errors on an openhab restart.

Full details over at https://community.openhab.org/t/zwave-deserialization-errors-with-1-80/7406 , summarized below.  (Go there for full examples, which I can't seem to figure out how to copy/paste here without the formatting mangling to heck and back.)

Observed with openhab 1.80.

Only seems to happen with GE/Jasco devices.

Example of NULLs embedded into zwave xml files:

<pre><code>
      <commandClass>NODE_NAMING</commandClass>
      <nameLocationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <initialiseName>true</initialiseName>
        <initialiseLocation>true</initialiseLocation>
       <name>Garage lights&#x0;&#x0;&#x0;</name>
      </nameLocationCommandClass>

       <nameLocationCommandClass>
                <version>1</version>
                <instances>1</instances>
                <initialiseName>true</initialiseName>
                <initialiseLocation>true</initialiseLocation>
                <name>Patio Lights&#x0;&#x0;&#x0;&#x0;</name>
              </nameLocationCommandClass>

    <entry>
      <commandClass>NODE_NAMING</commandClass>
      <nameLocationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <initialiseName>true</initialiseName>
        <initialiseLocation>true</initialiseLocation>
       <name>UH Stair light&#x0;&#x0;</name>
      </nameLocationCommandClass>
    </entry>
</pre></code>

Typical error generated when restarting openHAB:

2016-02-10 12:39:57.481 [ERROR] [b.z.i.protocol.ZWaveController] - NODE 52: Restore from config: Error deserialising XML file. com.thoughtworks.xstream.converters.ConversionException:  : ParseError at [row,col]:[52,32]
Message: Character reference "&# :  : ParseError at [row,col]:[52,32]
Message: Character reference "&#
---- Debugging information ----
message             :  : ParseError at [row,col]:[52,32]
Message: Character reference "&#
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       :  : ParseError at [row,col]:[52,32]
Message: Character reference "&#
class               : java.lang.String
required-type       : java.lang.String
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : com.thoughtworks.xstream.converters.basic.StringConverter
path                : /node/supportedCommandClasses/entry[4]/nameLocationCommandClass/name
line number         : 52
class[1]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveNodeNamingCommandClass
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : java.util.HashMap
converter-type[2]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[3]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6

Suggested fix is for NULLs to be escaped while writing zwave XML persistence files so they don't break on reinitialization.  (They're escaped, but apparently not in a way that xstream.io understands.)  Alternative solution may be filtering out NULLs when writing persistence files, but not sure what knock-on effect that may have down the road.  (Just thinking out loud here.)

**Comment by 9037568** [comment]
Depends on the version of XML being used. I believe nulls are supported in
1.1, but not in 1.0.

Seems to me a better solution would be to eliminate the nulls from the
source.


This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TheKorn2** [comment]
Fixed via #4060 pull.

**Comment by Robert-D** [comment]
Sorry guys I'm completely new to OpenHab and happened to stumble upon this after googling errors I was seeing in the openhab.log file. 

I have updated both the runtime and the zwave bindings to 1.8.2, but still receive the following errors in the openhab.log file:

`2016-03-22 10:39:28.854 [INFO ] [.c.ZWaveNodeNamingCommandClass] - NODE 2: Node name: null
2016-03-22 10:39:28.906 [ERROR] [.c.ZWaveNodeNamingCommandClass] - NODE 2 : Node Name report error in message length`

AND
`2016-03-22 11:44:10.820 [ERROR] [b.z.i.protocol.ZWaveController] - NODE 3: Restore from config: Error deserialising XML file. com.thoughtworks.xstream.converters.ConversionException:  : ParseError at [row,col]:[70,20]
Message: Character reference "&# :  : ParseError at [row,col]:[70,20]
Message: Character reference "&#
---- Debugging information ----
message             :  : ParseError at [row,col]:[70,20]
Message: Character reference "&#
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       :  : ParseError at [row,col]:[70,20]
Message: Character reference "&#
class               : java.lang.String
required-type       : java.lang.String
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
wrapped-converter   : com.thoughtworks.xstream.converters.basic.StringConverter
path                : /node/supportedCommandClasses/entry[6]/nameLocationCommandClass/name
line number         : 70
class[1]            : org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveNodeNamingCommandClass
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : java.util.HashMap
converter-type[2]   : com.thoughtworks.xstream.converters.collections.MapConverter
class[3]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------`

I have attached the full opnehab.log file, and the node.xml files. The extensions have been renamed to .txt for uploading purposes.

My hardware setup is pretty simple:
1 Aeon Labs Z-Stick Gen 5 (Node 1)
1 GE 12729 - Dimmer (Node 2)
1 GE 12727 - Toggle Switch (Node 3)

[openhab.txt](https://github.com/openhab/openhab/files/184576/openhab.txt)
[node1.txt](https://github.com/openhab/openhab/files/184577/node1.txt)
[node2.txt](https://github.com/openhab/openhab/files/184580/node2.txt)
[node3.txt](https://github.com/openhab/openhab/files/184581/node3.txt)

**Comment by cdjackson** [comment]
I'll try and get a fix for this tomorrow as it was fixed already in int oh2 binding

**Comment by Robert-D** [comment]
Stupid question, but should I be using OH2 at this point? Is version 1 development pretty much done?

**Comment by cdjackson** [comment]
Up to you - the OH2 binding is in heavy development. It’s generally working well, but as there’s a lot of development going on, it is subject to some changes occasionally. Hopefully in the next few weeks it should become more fixed and then it might be a better option as it supports more features now.

I wouldn’t say OH1 support finished, but certainly the OH2 binding is receiving the majority of effort right now and OH1 binding work is likely to have less work done unless there’s a strong drive for people to remain with OH1 instead of OH2...
